/* Generated By:JavaCC: Do not edit this line. Ir1ParserConstants.java */
package ir1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Ir1ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 4;
  /** RegularExpression Id. */
  int Digit = 9;
  /** RegularExpression Id. */
  int Letter = 10;
  /** RegularExpression Id. */
  int IntLit = 11;
  /** RegularExpression Id. */
  int BoolLit = 12;
  /** RegularExpression Id. */
  int StrLit = 13;
  /** RegularExpression Id. */
  int Temp = 14;
  /** RegularExpression Id. */
  int Label = 15;
  /** RegularExpression Id. */
  int Id = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"goto\"",
    "\"if\"",
    "\"call\"",
    "\"return\"",
    "<Digit>",
    "<Letter>",
    "<IntLit>",
    "<BoolLit>",
    "<StrLit>",
    "<Temp>",
    "<Label>",
    "<Id>",
    "\"\\n\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"=\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!\"",
  };

}
