#!/bin/bash

# Script for running ir1/CodeGen
#
#  - it compares CodeGen's output with the .s.ref file
#
#  Usage:
#   ./run tst1/test01.ir  -- test a single program 
#   ./run tst1/test*.ir   -- test all programs
#
#

for i
do
	d=`dirname $i`
	f=`basename $i .ir`
	echo -n "$d/$f: "
	java ir1/CodeGen $d/$f.ir 1> $d/$f.s 2> $d/$f.err
	if [ -r $d/$f.s.ref ]; then
          diff -w $d/$f.s $d/$f.s.ref > $d/$f.s.diff; 
          if [ -s $d/$f.s.diff ]; then 
            echo "differs from ref (see $f.s.diff)"; 
          else
            echo "matches ref"; 
            rm $d/$f.s.diff;
          fi
	else
            echo "no ref to compare"; 
        fi
	if [ -s $d/$f.err ]; then cat $d/$f.err; fi
done
exit 0

